baseURL = "https://janbechtel.de/cv"
languageCode = "de"
defaultContentLanguage = "de"
title = "Jan Bechtel"
theme = "hallo"
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm"]

[Author]
    name = "Jan"

[params]
    
    greeting = "Gude!"

    [params.colors]
        background = "#004c4c"

    [[params.links]]
        iconset = "fas"
        icon = "envelope"
        title = "E-mail"
        url = "mailto:mail@example.org"

    [[params.links]]
        icon = "github"
        title = "Github"
        url = "https://github.com/"

    [[params.links]]
        icon = "twitter"
        title = "Twitter"
        url = "https://twitter.com/"
      
