baseURL = "https://janbechtel.de/cv"
languageCode = "de"
defaultContentLanguage = "de"
title = "Jan"
theme = "hallo"
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm"]

[Author]
    name = "Jan"

[params]
    
    greeting = "Gude!"

    [params.colors]
        background = "#004c4c"

    [[params.links]]
        icon = "github"
        title = "Github"
        url = "https://github.com/"

