on: 
  push:
    paths:
      - "**/cv/**"

name: 🚀 Deploy Hugo
jobs:
  build:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2.4.0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          hugo-version: '0.89.4'
          extended: true

      - name: Build
        run: hugo --minify
        working-directory: ./cv/

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWD }}
          local-dir: ./cv/public/
          server-dir: ${{ secrets.FTP_DIR }}/cv/
